sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '4'
before_install:
- |
  npm i -g npm@^2.0.0
before_script:
- |
  gem update --system
  gem --version
  npm prune
script:
- echo test
before_deploy:
- gem install mime-types -v 2.6.2
